name: scorecode
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  score-code:
     runs-on: "ubuntu-latest"
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
       - name: JET2HOLIDAY
         run: echo "DARLING HOLD MY HANDðŸ¥µâ€¼ï¸ðŸ—£ï¸ðŸ—£ï¸NOTHING BEATS A JET 2 HOLIDAY ðŸ”¥ðŸ˜­ðŸ™ðŸ”›ðŸ”ðŸ”ðŸ—£ï¸ðŸ—£ï¸ðŸ—£ï¸ðŸ—£ï¸AND RIGHT NOW YOU SAVE 50 POUNDS ðŸ’·ðŸ’·ðŸ’· PER PERSONðŸ—£ðŸ”ŠðŸ”ŠðŸ”¥â€¼ï¸â€¼ï¸â€¼ï¸â€¼ï¸THAT'S 200 ðŸ’· ðŸ’· ðŸ’· OFF FOR A FAMILY OF 4 ðŸ—£ï¸ðŸ—£ï¸ðŸ—£ï¸ðŸ”¥ðŸ”¥ðŸ”¥ðŸ’¯ ðŸ’¯ ðŸ’¯ðŸ’ƒðŸ»ðŸ’ƒðŸ»ðŸ’ƒðŸ»ðŸ’ƒðŸ»ðŸ’ƒðŸ»"
         shell: bash
       - name: Install fuck-u-code
         run : go install github.com/Done-0/fuck-u-code/cmd/fuck-u-code@latest
         shell: bash
       - name: "Scan package(s)"
         run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          fuck-u-code analyze --verbose . > score.txt
          ls 
         shell: bash
       - name: upload result
         uses: actions/upload-artifact@v4
         with:
           name: score
           path: score.txt
       - name: getscore
         run: |
          fuck-u-code analyze -s .
       - name: commit score
         uses: stefanzweifel/git-auto-commit-action@v6
         with:
           commit_message: "commit shit-code-score"
           branch: main
